package command

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	gear "github.com/azuyamat/gear/command"
	"github.com/azuyamat/pace/internal/config/schema"
)

var schemaCommand = gear.NewExecutableCommand("schema", "Print or generate Pace language schema artifacts").
	Flags(
		gear.NewBoolFlag("json", "j", "Output the Pace language schema as JSON", false),
		gear.NewBoolFlag("generate-vscode", "", "Generate VS Code extension artifacts from the Go schema", false),
		gear.NewStringFlag("out", "o", "VS Code extension directory for generated artifacts", "vscode-pace"),
	).
	Handler(schemaHandler)

func init() {
	RootCommand.AddChild(schemaCommand)
}

func schemaHandler(ctx *gear.Context, args gear.ValidatedArgs) error {
	lang := schema.Get()
	if args.FlagBool("generate-vscode") {
		return generateVSCodeArtifacts(args.FlagString("out"), lang)
	}
	if args.FlagBool("json") {
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(lang)
	}
	fmt.Fprintln(os.Stdout, "Use --json to print the schema or --generate-vscode to regenerate extension artifacts.")
	return nil
}

func generateVSCodeArtifacts(outDir string, lang schema.LanguageSchema) error {
	if err := os.MkdirAll(filepath.Join(outDir, "src", "generated"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(outDir, "schemas"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(outDir, "syntaxes"), 0o755); err != nil {
		return err
	}

	jsonBytes, err := json.MarshalIndent(lang, "", "  ")
	if err != nil {
		return err
	}
	jsonBytes = append(jsonBytes, '\n')
	if err := os.WriteFile(filepath.Join(outDir, "schemas", "pace.schema.json"), jsonBytes, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "src", "generated", "paceSchema.ts"), []byte(tsSchema(lang)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "src", "generated", "schemaSnippets.ts"), []byte(tsSnippets(lang)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "syntaxes", "pace.generated-keywords.json"), []byte(generatedKeywords(lang)), 0o644); err != nil {
		return err
	}
	if err := mergeGrammarKeywords(filepath.Join(outDir, "syntaxes", "pace.tmLanguage.json"), lang); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "LANGUAGE_REFERENCE.generated.md"), []byte(languageReference(lang)), 0o644)
}

func tsSchema(lang schema.LanguageSchema) string {
	bytes, _ := json.MarshalIndent(lang, "", "  ")
	return "// Code generated by `go run ./cmd/pace schema --generate-vscode`; DO NOT EDIT.\n" +
		"export const paceSchema = " + string(bytes) + " as const;\n"
}

func tsSnippets(lang schema.LanguageSchema) string {
	return `// Code generated by ` + "`go run ./cmd/pace schema --generate-vscode`" + `; DO NOT EDIT.
import * as vscode from 'vscode';
import { paceSchema } from './paceSchema';
import type { SnippetsConfig } from '../snippets.config';

function kindFor(type: string): vscode.CompletionItemKind | undefined {
    return type === 'boolean' ? vscode.CompletionItemKind.Keyword : undefined;
}

function propertyDetail(context: string, type: string): string {
    return 'Pace ' + context + ' property (' + type + ')';
}

function deprecated(item: unknown): boolean | undefined {
    return (item as { deprecated?: boolean }).deprecated;
}

export const generatedSnippetsConfig: SnippetsConfig = {
    topLevel: paceSchema.topLevel.map(item => ({
        label: item.name,
        snippet: item.snippet,
        documentation: item.description,
        detail: 'Pace top-level statement',
        deprecated: deprecated(item)
    })),
    taskProperties: paceSchema.taskProperties.map(item => ({
        label: item.name,
        snippet: item.snippet,
        documentation: item.description,
        kind: kindFor(item.type),
        detail: propertyDetail('task', item.type),
        deprecated: deprecated(item)
    })),
    hookProperties: paceSchema.hookProperties.map(item => ({
        label: item.name,
        snippet: item.snippet,
        documentation: item.description,
        kind: kindFor(item.type),
        detail: propertyDetail('hook', item.type),
        deprecated: deprecated(item)
    })),
    argsProperties: paceSchema.argsProperties.map(item => ({
        label: item.name,
        snippet: item.snippet,
        documentation: item.description,
        kind: kindFor(item.type),
        detail: propertyDetail('args', item.type),
        deprecated: deprecated(item)
    }))
};
`
}

func generatedKeywords(lang schema.LanguageSchema) string {
	top := namesFromStatements(lang.TopLevel)
	task := namesFromProperties(lang.TaskProps)
	hook := namesFromProperties(lang.HookProps)
	args := namesFromProperties(lang.ArgsProps)
	return fmt.Sprintf("{\n  \"note\": \"Code generated by go run ./cmd/pace schema --generate-vscode; DO NOT EDIT. pace.tmLanguage.json keyword patterns are merged from this schema.\",\n  \"topLevel\": \"%s\",\n  \"taskProperties\": \"%s\",\n  \"hookProperties\": \"%s\",\n  \"argsProperties\": \"%s\"\n}\n",
		strings.Join(top, "|"), strings.Join(task, "|"), strings.Join(hook, "|"), strings.Join(args, "|"))
}

func mergeGrammarKeywords(path string, lang schema.LanguageSchema) error {
	bytes, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	content := string(bytes)
	top := strings.Join(namesFromStatements(lang.TopLevel), "|")
	props := append(namesFromProperties(lang.TaskProps), namesFromProperties(lang.HookProps)...)
	props = append(props, namesFromProperties(lang.ArgsProps)...)
	content = replaceMatchAfterScope(content, "keyword.control.pace", "\\\\b("+top+")\\\\b")
	content = replaceMatchAfterScope(content, "keyword.other.pace", "\\\\b("+uniqueJoined(props)+")\\\\b")
	return os.WriteFile(path, []byte(content), 0o644)
}

func replaceMatchAfterScope(content, scope, match string) string {
	scopeIndex := strings.Index(content, "\"name\": \""+scope+"\"")
	if scopeIndex == -1 {
		return content
	}
	matchKey := "\"match\": \""
	matchIndex := strings.Index(content[scopeIndex:], matchKey)
	if matchIndex == -1 {
		return content
	}
	start := scopeIndex + matchIndex + len(matchKey)
	end := start
	for end < len(content) {
		if content[end] == '"' && content[end-1] != '\\' {
			break
		}
		end++
	}
	return content[:start] + match + content[end:]
}

func uniqueJoined(items []string) string {
	seen := map[string]bool{}
	unique := make([]string, 0, len(items))
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			unique = append(unique, item)
		}
	}
	return strings.Join(unique, "|")
}

func languageReference(lang schema.LanguageSchema) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./cmd/pace schema --generate-vscode`; DO NOT EDIT. -->\n\n")
	b.WriteString("# Pace Language Reference\n\n")
	b.WriteString("## Top-level statements\n\n")
	for _, item := range lang.TopLevel {
		fmt.Fprintf(&b, "- `%s` — %s\n", item.Name, item.Description)
	}
	b.WriteString("\n## Task properties\n\n")
	for _, item := range lang.TaskProps {
		fmt.Fprintf(&b, "- `%s` (`%s`) — %s\n", item.Name, item.Type, item.Description)
	}
	b.WriteString("\n## Hook properties\n\n")
	for _, item := range lang.HookProps {
		fmt.Fprintf(&b, "- `%s` (`%s`) — %s\n", item.Name, item.Type, item.Description)
	}
	b.WriteString("\n## Args properties\n\n")
	for _, item := range lang.ArgsProps {
		fmt.Fprintf(&b, "- `%s` (`%s`) — %s\n", item.Name, item.Type, item.Description)
	}
	return b.String()
}

func namesFromStatements(items []schema.Statement) []string {
	names := make([]string, 0, len(items))
	for _, item := range items {
		names = append(names, item.Name)
	}
	return names
}

func namesFromProperties(items []schema.Property) []string {
	names := make([]string, 0, len(items))
	for _, item := range items {
		names = append(names, item.Name)
	}
	return names
}
